navigation:
  - name: "About Me"
    link: "#about-me"
  - name: "Education"
    link: "#education"
  - name: "Skills"
    link: "#skills"
  - name: "Professional Experience"
    link: "#professional-experience"
  - name: "Projects"
    link: "#projects"
  - name: "Publications"
    link: "#publications"
  - name: "Research Publications"
    link: "#research-publications"

title: Nirmal S. Nair
logo: /assets/img/logo.webp
email: nirmal.nair@outlook.com
description: 3D Reconstruction | SLAM | Virtual Reality 
favicon: true
remote_theme: vaibhavvikas/jekyll-theme-minimalistic
color-scheme: dark

google_analytics:

url: "https://nirmalsnair.github.io/"

plugins:
  - jekyll-seo-tag
  - jemoji
  - jekyll-remote-theme
  - jekyll-sitemap

platforms:
  - name: Google Scholar
    icon: <svg xmlns="http://www.w3.org/2000/svg" aria-hidden="true" role="img" style="vertical-align:-0.125em;" width="1em" height="1em" preserveAspectRatio="xMidYMid meet" viewBox="0 0 24 24"><path d="M5.242 13.769L0 9.5L12 0l12 9.5l-5.242 4.269C17.548 11.249 14.978 9.5 12 9.5c-2.977 0-5.548 1.748-6.758 4.269zM12 10a7 7 0 1 0 0 14a7 7 0 0 0 0-14z" fill="currentColor"/></svg>
    link: https://scholar.google.com/citations?user=oebmvdEAAAAJ
  - name: ORCID
    icon: <i class="fa-brands fa-orcid"></i>
    link: https://orcid.org/0000-0002-6555-6961
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/nirmalsnair
  - name: LinkedIn
    icon: <i class="fa-brands fa-linkedin"></i>
    link: https://www.linkedin.com/in/nrml/

github: [metadata]