#!/bin/sh

set -e

bundle exec jekyll build
bundle exec htmlproofer ./_site --check-html --url-ignore '/fonts.gstatic.com/,/dl.acm.org/,/scholar.google.com/,/www.linkedin.com/' --allow-missing-href --allow-hash-href
bundle exec rubocop -D --config .rubocop.yml
bundle exec script/validate-html
